# Generated by Django 5.2.1 on 2025-06-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_rename_issue_category_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='issue_type',
            field=models.CharField(max_length=50),
        ),
    ]
